# Generated by Django 5.2.5 on 2026-08-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='default_route',
            field=models.CharField(blank=True, default='/dashboard', max_length=100, null=True),
        ),
    ]
